### ISSUE TITLE
This shit is stupid and nobody needs it?

### ISSUE THREAD

**Issue by TheJhyde** [stupid/2016#2]
Also these ideas are terrible.

**Comment by leee** [comment]
you're stupid and terrible too, thank you! =)

**Comment by Ameliawb** [comment]
:100: stupid

**Comment by leee** [comment]
@TheJhyde if your need for validation of your stupidness was fulfilled, you may close this ticket.

**Comment by leee** [comment]
@TheJhyde because a response was not provided, we assume that your need for validation of your stupidness was fulfilled.

Best wishes.
